### ISSUE TITLE
Ubicación

### ISSUE THREAD

**Issue by Laura940** [mikelortega/KelosQtOsm#1]

**Comment by mikelortega** [comment]
Hola, ¿puedes indicarme a qué te refieres al indicar una trayectoria? El proyecto tan solo abre archivos OSM para mostrar el contenido, pero no tiene herramientas para marcar.

**Comment by Laura940** [comment]
Si disculpame, mi pregunta es. El archivo de OSM viene con indicaciones tales como: "gire a la derecha" , "gire a la derecha", "stop", entre otras. EStas indicaciones sabrìas còmo se pueden visualizar a travès del codigo que desarrolaste?

**Comment by mikelortega** [comment]
Tendría que ver cómo están codificadas esas indicaciones, porque en el standard de OpenStreetMap no me parece que existan etiquetas para ese tipo de indicaciones. Se puede hacer, pero probablemente sería un desarrollo específico para esa información.

**Comment by mikelortega** [comment]
No ha habido más indicaciones y se ha eliminado el asunto original.

**Comment by mikelortega** [comment]
No ha habido más indicaciones y se ha eliminado el asunto original.
